=== lucasronchetti/acnh-api/docs/schema/v1/fish.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "array",
  "title": "The Root Schema",
  "description": "The root schema comprises the entire JSON document.",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The fish schema",
    "required": ["name", "shadowSize", "location", "time", "price", "month"],
    "properties": {
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "Fish name"
      },
      "shadowSize": {
        "$id": "#/items/properties/shadowSize",
        "type": "string",
        "title": "Fish's shadow size"
      },
      "location": {
        "$id": "#/items/properties/location",
        "type": "string",
        "title": "Fish's location",
        "description": "Where this fish can be found"
      },
      "time": {
        "$id": "#/items/properties/time",
        "type": "string",
        "title": "Time of day",
        "description": "time of day when this fish can be found"
      },
      "price": {
        "$id": "#/items/properties/price",
        "type": "integer",
        "title": "Fish's price"
      },
      "month": {
        "$id": "#/items/properties/month",
        "type": "object",
        "title": "Time of month",
        "description": "time of month when this fish can be found",
        "required": ["north", "south"],
        "properties": {
          "north": {
            "$id": "#/items/properties/month/properties/north",
            "type": "array",
            "title": "Northern hemisphere schedule",
            "items": {
              "$id": "#/items/properties/month/properties/north/items",
              "type": "integer",
              "title": "Month",
              "description": "Integer representation of the month"
            }
          },
          "south": {
            "$id": "#/items/properties/month/properties/south",
            "type": "array",
            "title": "Southern hemisphere schedule",
            "items": {
              "$id": "#/items/properties/month/properties/south/items",
              "type": "integer",
              "title": "Month",
              "description": "Integer representation of the month"
            }
          }
        }
      }
    }
  }
}

=== lucasronchetti/acnh-api/docs/data/v1/fish.json
[
  {
    "name": "Bitterling",
    "shadowSize": "1",
    "location": "River",
    "time": "All day",
    "price": 900,
    "month": {
      "north": [1, 2, 3, 11, 12],
      "south": [5, 6, 7, 8, 9]
    }
  },
  {
    "name": "Pale Chub",
    "shadowSize": "1",
    "location": "River",
    "time": "9 AM - 4 PM",
    "price": 200,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Crucian Carp",
    "shadowSize": "2",
    "location": "River",
    "time": "All day",
    "price": 160,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Dace",
    "shadowSize": "3",
    "location": "River",
    "time": "4 PM - 9 AM",
    "price": 240,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Carp",
    "shadowSize": "4",
    "location": "Pond",
    "time": "All day",
    "price": 300,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Koi",
    "shadowSize": "4",
    "location": "Pond",
    "time": "4 PM - 9 AM",
    "price": 4000,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Goldfish",
    "shadowSize": "1",
    "location": "Pond",
    "time": "All day",
    "price": 1300,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Pop-eyed goldfish",
    "shadowSize": "1",
    "location": "Pond",
    "time": "9 AM - 4 PM",
    "price": 1300,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Ranchu goldfish",
    "shadowSize": "2",
    "location": "Pond",
    "time": "9 AM - 4 PM",
    "price": 4500,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Killifish",
    "shadowSize": "1",
    "location": "Pond",
    "time": "All day",
    "price": 300,
    "month": {
      "north": [4, 5, 6, 7, 8],
      "south": [1, 2, 10, 11, 12]
    }
  },
  {
    "name": "Crawfish",
    "shadowSize": "2",
    "location": "Pond",
    "time": "All day",
    "price": 200,
    "month": {
      "north": [4, 5, 6, 7, 8, 9],
      "south": [1, 2, 3, 10, 11, 12]
    }
  },
  {
    "name": "Soft-shelled Turtle",
    "shadowSize": "4",
    "location": "River",
    "time": "4 PM - 9 AM",
    "price": 3750,
    "month": {
      "north": [8, 9],
      "south": [2, 3]
    }
  },
  {
    "name": "Snapping turtle",
    "shadowSize": "5",
    "location": "River",
    "time": "9 PM - 4 AM",
    "price": 5000,
    "month": {
      "north": [4, 5, 6, 7, 8, 9, 10],
      "south": [1, 2, 3, 4, 10, 11, 12]
    }
  },
  {
    "name": "Tadpole",
    "shadowSize": "1",
    "location": "Pond",
    "time": "All day",
    "price": 100,
    "month": {
      "north": [3, 4, 5, 6, 7],
      "south": [1, 9, 10, 11, 12]
    }
  },
  {
    "name": "Frog",
    "shadowSize": "2",
    "location": "Pond",
    "time": "All day",
    "price": 120,
    "month": {
      "north": [5, 6, 7, 8],
      "south": [1, 2, 11, 12]
    }
  },
  {
    "name": "Freshwater Goby",
    "shadowSize": "2",
    "location": "River",
    "time": "4 PM - 9 AM",
    "price": 400,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  },
  {
    "name": "Loach",
    "shadowSize": "2",
    "location": "River",
    "time": "All day",
    "price": 400,
    "month": {
      "north": [3, 4, 5],
      "south": [9, 10, 11]
    }
  },
  {
    "name": "Catfish",
    "shadowSize": "4",
    "location": "Pond",
    "time": "4 PM - 9 AM",
    "price": 800,
    "month": {
      "north": [5, 6, 7, 8, 9, 10],
      "south": [1, 2, 3, 4, 11, 12]
    }
  },
  {
    "name": "",
    "shadowSize": "",
    "location": "",
    "time": "",
    "price": 0,
    "month": {
      "north": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      "south": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    }
  }
]
